"""CLI constants to avoid magic numbers."""

from __future__ import annotations

from ..application.constants import WALLS_DEFAULT as APP_WALLS_DEFAULT

PLAYER_COUNT_MIN = 2
PLAYER_COUNT_MAX = 4
PLAYER_COUNT_SUPPORTED = {2, 3, 4}
PLAYER_ID_MIN = 1
PLAYER_ID_MAX = 4

BOARD_SIZE_MIN = 3
BOARD_SIZE_MAX = 15
BOARD_SIZE_DEFAULT = 9
WALLS_DEFAULT = APP_WALLS_DEFAULT

AI_MODE_MINIMAX = "minimax"
AI_MODE_ITERATIVE = "iterative"
AI_MODE_MCTS = "mcts"
AI_MODE_DEFAULT = AI_MODE_ITERATIVE
AI_TIME_DEFAULT = 5
AI_MINIMAX_DEPTH_DEFAULT = None

WALL_TOKEN_MIN_LENGTH = 3
UNBALANCED_PLAYERS_COUNT = 3
